version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - checkout
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint


